export const ADD_FACULTY = 'ADD_FACULTY'
export const ADD_GROUP = 'ADD_GROUP'
export const DELETE_FACULTY = 'DELETE_FACULTY'
export const DELETE_GROUP = "DELETE_GROUP";
export const DELETE_STUDENT = "DELETE_STUDENT";
export const FACULTY_INPUT_CHANGE = "INPUT_CHANGE";
export const GROUP_INPUT_CHANGE = "GROUP_INPUT_CHANGE";
export const ACCEPT_CHANGES = 'ACCEPT_CHANGES'
export const ACCEPT_CHANGES_GROUP = "ACCEPT_CHANGES_GROUP";
export const CLOSE_EDIT_FACULTY = "CLOSE_EDIT_FACULTY";

export const ADD_STUDENT = "ADD_STUDENT";
export const STUDENT_INPUT_CHANGE = "STUDENT_INPUT_CHANGE";
export const ACCEPT_CHANGES_STUDENT = "ACCEPT_CHANGES_STUDNET";
export const FILTER_STUDENTS = "FILTER_STUDENTS";
export const SEARCH_TYPINGS = "SEARCH_TYPINGS";
export const CLEAR_TYPINGS_SEARCH = "CLEAR_TYPINGS_SEARCH"
export const CLOSE_EDIT_STUDNET = "CLOSE_EDIT_STUDNET";
export const CREATE_PROJECT = "CREATE_PROJECT";

export const GET_FACULTIES = "GET_FACULTIES";
export const GET_GROUPS = "GET_FACULTY";
export const GET_STUDENTS = "GET_STUDENTS";




